"""empty message

Revision ID: 282a3a88ebe6
Revises: f13dee2b0c06
Create Date: 2022-01-31 13:00:02.153118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282a3a88ebe6'
down_revision = 'f13dee2b0c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
