"""empty message

Revision ID: 36def8f97488
Revises: 35bcebd4084a
Create Date: 2022-01-31 13:53:48.725193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36def8f97488'
down_revision = '35bcebd4084a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
