"""empty message

Revision ID: 7ee1f632af68
Revises: 36def8f97488
Create Date: 2022-01-31 14:00:27.817844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ee1f632af68'
down_revision = '36def8f97488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
