"""empty message

Revision ID: e70cb947a43f
Revises: 03bb8e740e58
Create Date: 2022-01-26 15:05:31.386871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70cb947a43f'
down_revision = '03bb8e740e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('article', sa.Column('slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'slug')
    op.drop_column('article', 'author')
    # ### end Alembic commands ###
